-- Q1 What is the total revenue generated by male vs female customers?

SELECT 
    gender,
    SUM(purchase_amount) AS total_revenue
FROM public.customer
GROUP BY gender
ORDER BY total_revenue DESC;



-- Q2 Which customers used a discount but still spent more than the average purchase amount?

SELECT 
    *
FROM public.customer
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount)
    FROM public.customer
);



-- Q3 Which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased,
    AVG(review_rating) AS avg_review_rating
FROM public.customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;



-- Q4 Compare the average purchase amounts between Standard and Express Shipping

SELECT 
    shipping_type,
    AVG(purchase_amount) AS avg_purchase_amount
FROM public.customer
GROUP BY shipping_type;



-- Q5 Do subscribed customers spend more Compare average spend and total revenue between subscribers and non-subscribers

SELECT 
    subscription_status,
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM public.customer
GROUP BY subscription_status;



-- Q6 Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased,
    COUNT(*) FILTER (WHERE discount_applied = 'Yes') * 100.0 / COUNT(*) AS discount_percentage
FROM public.customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;



-- Q7 Segment customers into New Returning and Loyal based on their total number of previous purchases and show the count of each segment

SELECT 
    CASE
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM public.customer
GROUP BY customer_segment;



-- Q8 What are the top 3 most purchased products within each category?

SELECT 
    category,
    item_purchased,
    purchase_count
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rank
    FROM public.customer
    GROUP BY category, item_purchased
) ranked
WHERE rank <= 3;



-- Q9 Are customers who are repeat buyers more than 5 previous purchases also likely to subscribe?

SELECT 
    subscription_status,
    COUNT(*) AS repeat_customer_count
FROM public.customer
WHERE previous_purchases > 5
GROUP BY subscription_status;



-- Q10 What is the revenue contribution of each age group?

SELECT 
    CASE
        WHEN age < 25 THEN 'Young'
        WHEN age BETWEEN 25 AND 45 THEN 'Adult'
        WHEN age BETWEEN 46 AND 60 THEN 'Middle Age'
        ELSE 'Senior'
    END AS age_group,
    SUM(purchase_amount) AS total_revenue
FROM public.customer
GROUP BY age_group
ORDER BY total_revenue DESC;